// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCTOp4CjtuqwozCRabNkykyRgWs0zlbw',
    appId: '1:1012695789817:web:34ebdb00db8292a2e2b228',
    messagingSenderId: '1012695789817',
    projectId: 'do-an-di-dong-8aa6a',
    authDomain: 'do-an-di-dong-8aa6a.firebaseapp.com',
    storageBucket: 'do-an-di-dong-8aa6a.firebasestorage.app',
    measurementId: 'G-4QR71VQKL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejFeYZnNoPyxBL2LQ6nDEwmGZ_a87Ra8',
    appId: '1:1012695789817:android:a5d21e6913689cfae2b228',
    messagingSenderId: '1012695789817',
    projectId: 'do-an-di-dong-8aa6a',
    storageBucket: 'do-an-di-dong-8aa6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHeAn_SR6lTt-BHXas1AKTmqoswPw8kU',
    appId: '1:1012695789817:ios:366b52e1bd2fed1ae2b228',
    messagingSenderId: '1012695789817',
    projectId: 'do-an-di-dong-8aa6a',
    storageBucket: 'do-an-di-dong-8aa6a.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHeAn_SR6lTt-BHXas1AKTmqoswPw8kU',
    appId: '1:1012695789817:ios:366b52e1bd2fed1ae2b228',
    messagingSenderId: '1012695789817',
    projectId: 'do-an-di-dong-8aa6a',
    storageBucket: 'do-an-di-dong-8aa6a.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuCTOp4CjtuqwozCRabNkykyRgWs0zlbw',
    appId: '1:1012695789817:web:aceaea4c0ce1e269e2b228',
    messagingSenderId: '1012695789817',
    projectId: 'do-an-di-dong-8aa6a',
    authDomain: 'do-an-di-dong-8aa6a.firebaseapp.com',
    storageBucket: 'do-an-di-dong-8aa6a.firebasestorage.app',
    measurementId: 'G-4J419QR8ZB',
  );
}
